# Generated by Django 4.2.13 on 2024-05-16 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
